config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root 'public_recipes#index', as: :authenticated_root
  end

  unauthenticated do
    root 'public_recipes#splash', as: :unauthenticated_root
  end

  resources :foods, only: %i[index new create destroy]
  resources :recipes, except: :edit do
    resources :recipe_foods, only: %i[new create destroy]
  end
  resources :shopping_lists, only: %i[index]
  resources :public_recipes, only: %i[index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Food, user_id: user.id
      can :manage, Recipe, user_id: user.id
      can :manage, RecipeFood, recipe: { user_id: user.id }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipe, through: :recipe_foods

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }, allow_blank: false
  validates :measurement_unit, presence: true, allow_blank: false
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def to_buy
    recipe_foods.reduce(-quantity) do |sum, recipe_food|
      sum + recipe_food.quantity
    end
  end

  def name_with_measurement_unit
    "#{name} (#{measurement_unit})"
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }, allow_blank: false
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }, allow_blank: false
  validates :public, inclusion: { in: [true, false] }

  def show_description?(current_user)
    public || user.admin? || user == current_user
  end

  def owner?(current_user)
    user == current_user || user.admin?
  end

  def total_price
    recipe_foods.reduce(0) do |sum, recipe_food|
      sum + (recipe_food.food.price * recipe_food.quantity)
    end
  end

  def total_time
    preparation_time + cooking_time
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }, allow_blank: false

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @foods = @user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @user = current_user
    @food = @user.foods.new(food_params)

    if @food.save
      redirect_to foods_path, notice: t('.success')
    else
      redirect_to new_food_path, alert: t('.failure')
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: t('.success')
  rescue ActiveRecord::RecordNotFound
    redirect_to foods_path, alert: t('.failure')
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  before_action :authenticate_user!, except: [:splash]

  def index
    @recipes = Recipe.includes(:user, recipe_foods: [:food]).where(public: true).order('created_at DESC')
  end

  def splash; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: t('.success')
    else
      render :new, alert: t('.failure')
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipes = @user.recipes
  end

  def show
    @recipe = Recipe.includes(recipe_foods: [:food]).find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: t('.success')
    else
      render :new, alert: t('.failure')
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: t('.success')
  rescue ActiveRecord::RecordNotFound
    redirect_to recipes_path, alert: t('.failure')
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe), notice: t('.success')
  rescue ActiveRecord::RecordNotFound
    redirect_to recipe_path(@recipe), alert: t('.failure')
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :image, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods

    @items_to_buy = 0
    @needed_money = 0

    @foods.each do |food|
      @items_to_buy += 1 if food.to_buy.positive?
      @needed_money += food.to_buy * food.price if food.to_buy.positive?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/foods/index.html.erb
<%= render 'shared/header', back: false %>
<%= render 'shared/flash' %>

<div class="food-container">
    <h2> My Ingredients </h2>

    <% if @foods.length === 0 %>
        <p class="no-foods">You don't have any ingredients yet.</p>
    <% else %>
        <table>
            <thead>
                <tr>
                    <th>Ingredients</th>
                    <th>Unit</th>
                    <th>Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @foods.each do |food| %>
                    <tr>
                        <td><%= food.name %></td>
                        <td><%= food.measurement_unit %></td>
                        <td>$<%= food.price %></td>
                        <td>
                            <%= button_to 'Delete', food_path(food.id), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: 'btn-link warning large' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>

    <%= link_to "Add ingredient", new_food_path, class: 'btn-link' %>
</div>

app/views/foods/new.html.erb
<div class="form-container">
    <%= render 'shared/header', back: true %>
    <%= render 'shared/flash' %>
    <h2>Add New Ingredient</h2>

    <%= form_with model: @food, url: foods_path, scope: :food do |f| %>
        <div class="field">
            <%= f.text_field :name, required: true, placeholder: "name" %>
        </div>
        <div class="field">
            <%= f.text_field :measurement_unit, required: true, placeholder: "measurement unit" %>
        </div>
        <div class="field">
            <%= f.number_field :price, required: true, placeholder: "price (usd)", step: "0.01", value: "" %>
        </div>

        <div class="field">
            <%= f.number_field :quantity, required: true, placeholder: "Amount", step: "0.01", value: "" %>
        </div>

        <div>
            <%= f.submit "Add Ingredient" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'custom', "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<%= render 'shared/header', back: false %>
<%= render 'shared/flash' %>

<% if @recipes.empty? %>
    <h2>No Public Recipes found</h2>
<% else %>
    <h2>Public Recipes</h2>
    <ul class="recipes">
        <% @recipes.each do |recipe| %>
            <li>
                <%= link_to recipe_path(recipe) do %>
                    <div class="img">
                        <%= image_tag recipe.image %>
                    </div>
                    <p class="title"><%= recipe.name %></p>
                    <div class="info">
                        <p class="info-time"> 
                            <span>Total Time:</span>
                            <span>
                            <%= image_tag('watch.svg', alt: 'stop watch', class: 'watch' ) %>
                            <%= recipe.total_time %>
                            min
                            </span>
                        </p>
                        <p class="info-time">
                            <span>Total Price:</span>
                            <span class="move-down">$ <%= recipe.total_price %></span>
                        </p>
                    </div>
                    <p class="username">By: <span><%= recipe.user.name %></span></p>
                <% end %>
            </li>
        <% end %>
    </ul>
<% end %>
            

app/views/public_recipes/splash.html.erb
<div class="splash">
    <div class="splash-container">
        <div class="logo"><%= image_tag('logo.png', alt: 'Logo', class: 'logo-img' ) %></div>
        <p class="intro welcome">Welcome to the Recipe App!</p>
        <p class="intro">Please log in or sign up to get started.</p>
        <div class="link">
            <%= link_to "Log In", new_user_session_path %>
            <%= link_to "Sign Up", new_user_registration_path %>
        </div>
    </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="form-container">
  <%= render 'shared/header', back: true %>
  <%= render 'shared/flash' %>
  <h2>Add new ingredient to:</h2>
  <h3><%= @recipe.name %></h3>

  <%= form_with model: [@recipe, @recipe_food] do |form| %>
    <% @recipe_food.errors.full_messages.each do |error| %>
      <div><%= error %></div>
    <% end %>

    <div class="field">
      <%= form.collection_select :food_id, Food.order(:name), :id, :name_with_measurement_unit, { prompt: "Choose ingredients" }, { value: "" } %>
    </div>

    <div class="field">
      <%= form.number_field :quantity, placeholder: "amount", step: "0.01" %>
    </div>

    <%= form.submit t('.submit') %>
  <% end %>
</div>

app/views/recipes/_recipe.html.erb
<li>
  <%= link_to recipe_path(recipe) do %>
      <div class="img">
          <%= image_tag recipe.image %>
      </div>
      <p class="title recipe-title"><%= recipe.name %></p>
      <div class="info recipe-info">
          <p class="info-time"> 
            <span>Prep Time:</span>
            <span>
              <%= image_tag('watch.svg', alt: 'stop watch', class: 'watch' ) %>
              <%= recipe.preparation_time %>
              min
            </span>
          </p>
          <p class="info-time">
            <span>Cook Time:</span>
            <span>
              <%= image_tag('watch.svg', alt: 'stop watch', class: 'watch' ) %>
              <%= recipe.cooking_time %>
              min
            </span>
          </p>
      </div>
  <% end %>
</li>

app/views/recipes/index.html.erb
<%= render 'shared/header', back: false %>
<%= render 'shared/flash' %>

<div class="fullHeight">
  <h2>My Recipes</h2>

  <% if @recipes.length === 0 %>
    <p class="no-recipes">You don't have any recipes yet.</p>
  <% else %>
    <ul class="recipes">
      <%= render partial: 'recipe', collection: @recipes, locals: {recipe: @recipe}  %>
    </ul>
  <% end %>

  <div class="recipe-btn">
    <%= link_to t('.new'), new_recipe_path, class: 'btn-link' %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="form-container">
  <%= render 'shared/header', back: true %>
  <%= render 'shared/flash' %>
  <h2> <%= t('.title') %> </h2>
  <%= form_with model: @recipe do |form| %>
    <% @recipe.errors.full_messages.each do |error| %>
      <div><%= error %></div>
    <% end %>
    <div class="field">
      <%= form.text_field :name, placeholder: "name", required: true %>
    </div>

    <div class="field">
      <%= form.number_field :preparation_time, placeholder: "perparation time (mins)", value: "", required: true %>
    </div>

    <div class="field">
      <%= form.number_field :cooking_time, placeholder: "cooking time (mins)", value: "", required: true %>
    </div>

    <div class="field">
      <%= form.text_area :description, placeholder: "description", required: true %>
    </div>

    <div class="field">
      <%= form.text_area :image, placeholder: "Image url (optional)", value: "" %>
    </div>

    <div class="checkbox">
      <%= form.check_box :public%>
      <%= form.label :share_to_public?%>
    </div>

    <%= form.submit %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/header', back: true %>
<%= render 'shared/flash' %>


<div class="recipe-container">
  <div class="img desktop-img">
    <%= image_tag @recipe.image %>
  </div>

  <h4><%= @recipe.name %></h4>
  <div class="desktop-container">
    <div class="padded">
      <% if @recipe.show_description?(current_user) %>
        <p class="desc"><%= @recipe.description %></p>
      <% end %>

      <div class="time-container">
        <div>
          <p class="bold"><%= t('.preparation_time') %></p>
          <p><%= pluralize(@recipe.preparation_time, 'min') %></p>
        </div>
        <div>
          <p class="bold"><%= t('.cooking_time') %></p>
          <p><%= pluralize(@recipe.cooking_time, 'min') %></p>
        </div>
      </div>

      <div class="public-container">
        <div class="public">
          <% if @recipe.owner?(current_user) %>
            <%= form_with model: @recipe do |form| %>
              <% @recipe.errors.full_messages.each do |error| %>
                <div><%= error %></div>
              <% end %>
              <div>
                <%= form.check_box :public, onchange: 'this.form.submit();' %>
                <%= form.label :public %>
              </div>
            <% end %>
          <% end %>
        </div>
        <% if can? :detroy, @recipe %>
          <%= link_to(t('common.remove'), recipe_path(@recipe), data: {
            turbo_method: :delete,
            turbo_confirm: t('.confirm_delete')
          }, class: 'btn-link warning small')%>
        <% end %>
      </div>
    </div>
    <div class="padded-768px">
      <table>
        <thead>
          <tr>
            <th><%= t('.name') %></th>
            <th><%= t('.quantity') %></th>
            <th><%= t('.price') %></th>
          </tr>
        </thead>
        <tbody>
          <% @recipe.recipe_foods.each do |recipe_food| %>
            <tr>
              <td><%= recipe_food.food.name %></td>
              <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %> </td>
              <td>$<%= recipe_food.food.price * recipe_food.quantity %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="button-container">
        <%= link_to t('.generate_shopping_list'), shopping_lists_path, class: 'btn-link' %>

        <% if @recipe.owner?(current_user) %>
          <%= link_to t('.add_ingredient'), new_recipe_recipe_food_path(@recipe), class: 'btn-link' %>
        <% else %>
          <%= link_to "Add Recipe", new_recipe_path, class: 'btn-link' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_header.html.erb
<header>
  <% if back %>
    <button class="back"><%= image_tag('left-arrow.png', alt: 'left arrow', class: 'back-icon' ) %></button>
  <% else %>
    <h1><%= t('appTitle') %></h1>
  <% end %>
  <nav>
    <ul class="nav-link">
      <li><%= link_to t('.public_recipes'), public_recipes_path %></li>
      <li><%= link_to t('.my_recipes'), recipes_path %></li>
      <li><%= link_to "My Ingredients", foods_path %></li>
      <li><%= link_to t('.shopping_list'), shopping_lists_path %></li>

      <% if current_user %>
        <li><%= link_to "Logout (#{current_user.name})", destroy_user_session_path, data: {
          turbo_method: :delete, class: 'logout'
        } %></li>
      <% end %>
    </ul>
    <div class="hamburger">
      <span class="line"></span>
      <span class="line"></span>
      <span class="line"></span>
    </div>
  </nav>
</header>

app/views/shopping_lists/index.html.erb
<%= render 'shared/header', back: false %>
<%= render 'shared/flash' %>

<div class="shoppinglist-container">
    <h2 class="cart-title">
        <span>Shopping Cart</span>
        <span class="cart"><%= image_tag('cart.svg', alt: 'shopping cart') %></span>
    </h2>
    <div class="cart-info">
        <p>Amount of ingredients to buy: <%= @items_to_buy %></p>
        <p>Total price needed: $<%= @needed_money %></p>
    </div>
    <ul class="shoppingList">
        <li>
            <div class="bold">Product</div>
            <div class="bold">To buy</div>
            <div class="bold">Total price</div>
        </li>
        <% @foods.each do |food| %>
            <% if food.to_buy.positive? %>
                <li>
                    <div><%= food.name %></div>
                    <div><%= food.to_buy %><%= food.measurement_unit %></div>
                    <div>$<%= food.to_buy * food.price %></div>
                </li>
            <% end %>
        <% end %>
    </ul>
</div>